server:
  port: 8082
spring:
  application:
    name: fegin-find
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
  instance:
    hostname: eureka5
    metadata-map:
      cluster: turbineCluster
  #instance:
    #preferIpAddress: true